### ISSUE TITLE
Page with # in the title not working

### ISSUE THREAD

**Issue by joerod** [bugsio/confluence-domain-booster-plugin#1]
When we create a new page, with a "#" in the title (ie "Hashtag # Testing"), the page is created successfully, but when we click the link to that page on the 'Space Shortcuts' sidebar it says "Page Information - Page not found"
(url is - http://contoso.com/display/TES/Hashtag+#+Testing)
*This link points to the root domain

but when we click the link outside of the 'Space Shortcuts' (either on an embedded link in a document, or searching for the doc), it will feature the domainbooster url which WILL work.
(url is - http://contoso.com/display/TES/Hashtag+%23+Testing)
*note the use of the escape character for #, %23
is there something messed up in our config? or is this a known issue?
Thanks

**Comment by radomirml** [comment]
_(This was answered months ago via email, copying response here for completeness and closing)._

Hashes in URL have a special meaning (https://en.wikipedia.org/wiki/Fragment_identifier) so it's generally a bad idea to use it in file name on the web. Although you may see the hash i document title, the hash will always have to be encoded in document URL, otherwise it will be interpreted as URL fragment.

So, I suggest you avoid using hashes in file names (Confluence page titles). If that's not possible, when creating a shortcut, you'd probably have to use already encoded link as a shortcut. (If you don't encode it and use hash sign, Confluence will probably not encode it assuming it's URL fragment part.)
